### PR TITLE
12 out of 12 tests: Fix Incorrect Implementation and Module Path Impo…

### PR DESCRIPTION
**Pull request by DanielDaCosta**
This pull request addresses the issues in the implementation and incorrect module path imports in the test files.

**Changes Made:**

Corrected the implementation logic in the affected files.
Updated the module paths for the test files to ensure proper imports.

**Issue Fixed:**

Resolves issue https://github.com/radicalxdev/kai-ai-backend/issues/65.

Screenshot 2024-07-03 at 6 34 31 PM

### CODE REVIEW

**Review by mikhailocampo — COMMENTED** [review]
Looks also good

**Review by hash2004 — CHANGES_REQUESTED** [review]
LGTM, but the PR should be made to the STAGING branch.

**Comment by AaronSosaRamos** [comment]
Closed as this issue was solved in the new `Develop` branch

**Comment by AaronSosaRamos** [comment]
Closed as this issue was solved in the new Develop branch

**Pull request closed without merging**
